/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnforcerRouteImport } from './routes/enforcer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PnpRouteImport } from './routes/pnp'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as TreasuryRouteImport } from './routes/treasury'
import { Route as EnforcerCitationsRouteImport } from './routes/enforcer/citations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnforcerRoute = EnforcerRouteImport.update({
  id: '/enforcer',
  path: '/enforcer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PnpRoute = PnpRouteImport.update({
  id: '/pnp',
  path: '/pnp',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const TreasuryRoute = TreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => rootRouteImport,
} as any)
const EnforcerCitationsRoute = EnforcerCitationsRouteImport.update({
  id: '/citations',
  path: '/citations',
  getParentRoute: () => EnforcerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/enforcer': typeof EnforcerRouteWithChildren
  '/login': typeof LoginRoute
  '/pnp': typeof PnpRoute
  '/portal': typeof PortalRoute
  '/treasury': typeof TreasuryRoute
  '/enforcer/citations': typeof EnforcerCitationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enforcer': typeof EnforcerRouteWithChildren
  '/login': typeof LoginRoute
  '/pnp': typeof PnpRoute
  '/portal': typeof PortalRoute
  '/treasury': typeof TreasuryRoute
  '/enforcer/citations': typeof EnforcerCitationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/enforcer': typeof EnforcerRouteWithChildren
  '/login': typeof LoginRoute
  '/pnp': typeof PnpRoute
  '/portal': typeof PortalRoute
  '/treasury': typeof TreasuryRoute
  '/enforcer/citations': typeof EnforcerCitationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/enforcer'
    | '/login'
    | '/pnp'
    | '/portal'
    | '/treasury'
    | '/enforcer/citations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/enforcer'
    | '/login'
    | '/pnp'
    | '/portal'
    | '/treasury'
    | '/enforcer/citations'
  id:
    | '__root__'
    | '/'
    | '/enforcer'
    | '/login'
    | '/pnp'
    | '/portal'
    | '/treasury'
    | '/enforcer/citations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnforcerRoute: typeof EnforcerRouteWithChildren
  LoginRoute: typeof LoginRoute
  PnpRoute: typeof PnpRoute
  PortalRoute: typeof PortalRoute
  TreasuryRoute: typeof TreasuryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enforcer': {
      id: '/enforcer'
      path: '/enforcer'
      fullPath: '/enforcer'
      preLoaderRoute: typeof EnforcerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pnp': {
      id: '/pnp'
      path: '/pnp'
      fullPath: '/pnp'
      preLoaderRoute: typeof PnpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treasury': {
      id: '/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof TreasuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enforcer/citations': {
      id: '/enforcer/citations'
      path: '/citations'
      fullPath: '/enforcer/citations'
      preLoaderRoute: typeof EnforcerCitationsRouteImport
      parentRoute: typeof EnforcerRoute
    }
  }
}

interface EnforcerRouteChildren {
  EnforcerCitationsRoute: typeof EnforcerCitationsRoute
}

const EnforcerRouteChildren: EnforcerRouteChildren = {
  EnforcerCitationsRoute: EnforcerCitationsRoute,
}

const EnforcerRouteWithChildren = EnforcerRoute._addFileChildren(
  EnforcerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnforcerRoute: EnforcerRouteWithChildren,
  LoginRoute: LoginRoute,
  PnpRoute: PnpRoute,
  PortalRoute: PortalRoute,
  TreasuryRoute: TreasuryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
