/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as EnforcerRouteImport } from './routes/enforcer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PnpRouteImport } from './routes/pnp'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as TreasuryRouteImport } from './routes/treasury'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminManageRouteImport } from './routes/admin/manage'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as EnforcerIndexRouteImport } from './routes/enforcer/index'
import { Route as EnforcerCitationsRouteImport } from './routes/enforcer/citations'
import { Route as EnforcerNewRouteImport } from './routes/enforcer/new'
import { Route as TreasuryIndexRouteImport } from './routes/treasury/index'
import { Route as TreasuryCashierRouteImport } from './routes/treasury/cashier'
import { Route as TreasuryReportsRouteImport } from './routes/treasury/reports'
import { Route as TreasuryTransactionsRouteImport } from './routes/treasury/transactions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EnforcerRoute = EnforcerRouteImport.update({
  id: '/enforcer',
  path: '/enforcer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PnpRoute = PnpRouteImport.update({
  id: '/pnp',
  path: '/pnp',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const TreasuryRoute = TreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminManageRoute = AdminManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const EnforcerIndexRoute = EnforcerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnforcerRoute,
} as any)
const EnforcerCitationsRoute = EnforcerCitationsRouteImport.update({
  id: '/citations',
  path: '/citations',
  getParentRoute: () => EnforcerRoute,
} as any)
const EnforcerNewRoute = EnforcerNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EnforcerRoute,
} as any)
const TreasuryIndexRoute = TreasuryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TreasuryRoute,
} as any)
const TreasuryCashierRoute = TreasuryCashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => TreasuryRoute,
} as any)
const TreasuryReportsRoute = TreasuryReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => TreasuryRoute,
} as any)
const TreasuryTransactionsRoute = TreasuryTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => TreasuryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/enforcer': typeof EnforcerRouteWithChildren
  '/login': typeof LoginRoute
  '/pnp': typeof PnpRoute
  '/portal': typeof PortalRoute
  '/treasury': typeof TreasuryRouteWithChildren
  '/admin/manage': typeof AdminManageRoute
  '/admin/reports': typeof AdminReportsRoute
  '/enforcer/citations': typeof EnforcerCitationsRoute
  '/enforcer/new': typeof EnforcerNewRoute
  '/treasury/cashier': typeof TreasuryCashierRoute
  '/treasury/reports': typeof TreasuryReportsRoute
  '/treasury/transactions': typeof TreasuryTransactionsRoute
  '/admin/': typeof AdminIndexRoute
  '/enforcer/': typeof EnforcerIndexRoute
  '/treasury/': typeof TreasuryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pnp': typeof PnpRoute
  '/portal': typeof PortalRoute
  '/admin/manage': typeof AdminManageRoute
  '/admin/reports': typeof AdminReportsRoute
  '/enforcer/citations': typeof EnforcerCitationsRoute
  '/enforcer/new': typeof EnforcerNewRoute
  '/treasury/cashier': typeof TreasuryCashierRoute
  '/treasury/reports': typeof TreasuryReportsRoute
  '/treasury/transactions': typeof TreasuryTransactionsRoute
  '/admin': typeof AdminIndexRoute
  '/enforcer': typeof EnforcerIndexRoute
  '/treasury': typeof TreasuryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/enforcer': typeof EnforcerRouteWithChildren
  '/login': typeof LoginRoute
  '/pnp': typeof PnpRoute
  '/portal': typeof PortalRoute
  '/treasury': typeof TreasuryRouteWithChildren
  '/admin/manage': typeof AdminManageRoute
  '/admin/reports': typeof AdminReportsRoute
  '/enforcer/citations': typeof EnforcerCitationsRoute
  '/enforcer/new': typeof EnforcerNewRoute
  '/treasury/cashier': typeof TreasuryCashierRoute
  '/treasury/reports': typeof TreasuryReportsRoute
  '/treasury/transactions': typeof TreasuryTransactionsRoute
  '/admin/': typeof AdminIndexRoute
  '/enforcer/': typeof EnforcerIndexRoute
  '/treasury/': typeof TreasuryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/enforcer'
    | '/login'
    | '/pnp'
    | '/portal'
    | '/treasury'
    | '/admin/manage'
    | '/admin/reports'
    | '/enforcer/citations'
    | '/enforcer/new'
    | '/treasury/cashier'
    | '/treasury/reports'
    | '/treasury/transactions'
    | '/admin/'
    | '/enforcer/'
    | '/treasury/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pnp'
    | '/portal'
    | '/admin/manage'
    | '/admin/reports'
    | '/enforcer/citations'
    | '/enforcer/new'
    | '/treasury/cashier'
    | '/treasury/reports'
    | '/treasury/transactions'
    | '/admin'
    | '/enforcer'
    | '/treasury'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/enforcer'
    | '/login'
    | '/pnp'
    | '/portal'
    | '/treasury'
    | '/admin/manage'
    | '/admin/reports'
    | '/enforcer/citations'
    | '/enforcer/new'
    | '/treasury/cashier'
    | '/treasury/reports'
    | '/treasury/transactions'
    | '/admin/'
    | '/enforcer/'
    | '/treasury/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  EnforcerRoute: typeof EnforcerRouteWithChildren
  LoginRoute: typeof LoginRoute
  PnpRoute: typeof PnpRoute
  PortalRoute: typeof PortalRoute
  TreasuryRoute: typeof TreasuryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enforcer': {
      id: '/enforcer'
      path: '/enforcer'
      fullPath: '/enforcer'
      preLoaderRoute: typeof EnforcerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pnp': {
      id: '/pnp'
      path: '/pnp'
      fullPath: '/pnp'
      preLoaderRoute: typeof PnpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treasury': {
      id: '/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof TreasuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/manage': {
      id: '/admin/manage'
      path: '/manage'
      fullPath: '/admin/manage'
      preLoaderRoute: typeof AdminManageRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/enforcer/': {
      id: '/enforcer/'
      path: '/'
      fullPath: '/enforcer/'
      preLoaderRoute: typeof EnforcerIndexRouteImport
      parentRoute: typeof EnforcerRoute
    }
    '/enforcer/citations': {
      id: '/enforcer/citations'
      path: '/citations'
      fullPath: '/enforcer/citations'
      preLoaderRoute: typeof EnforcerCitationsRouteImport
      parentRoute: typeof EnforcerRoute
    }
    '/enforcer/new': {
      id: '/enforcer/new'
      path: '/new'
      fullPath: '/enforcer/new'
      preLoaderRoute: typeof EnforcerNewRouteImport
      parentRoute: typeof EnforcerRoute
    }
    '/treasury/': {
      id: '/treasury/'
      path: '/'
      fullPath: '/treasury/'
      preLoaderRoute: typeof TreasuryIndexRouteImport
      parentRoute: typeof TreasuryRoute
    }
    '/treasury/cashier': {
      id: '/treasury/cashier'
      path: '/cashier'
      fullPath: '/treasury/cashier'
      preLoaderRoute: typeof TreasuryCashierRouteImport
      parentRoute: typeof TreasuryRoute
    }
    '/treasury/reports': {
      id: '/treasury/reports'
      path: '/reports'
      fullPath: '/treasury/reports'
      preLoaderRoute: typeof TreasuryReportsRouteImport
      parentRoute: typeof TreasuryRoute
    }
    '/treasury/transactions': {
      id: '/treasury/transactions'
      path: '/transactions'
      fullPath: '/treasury/transactions'
      preLoaderRoute: typeof TreasuryTransactionsRouteImport
      parentRoute: typeof TreasuryRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminManageRoute: typeof AdminManageRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminManageRoute: AdminManageRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface EnforcerRouteChildren {
  EnforcerCitationsRoute: typeof EnforcerCitationsRoute
  EnforcerNewRoute: typeof EnforcerNewRoute
  EnforcerIndexRoute: typeof EnforcerIndexRoute
}

const EnforcerRouteChildren: EnforcerRouteChildren = {
  EnforcerCitationsRoute: EnforcerCitationsRoute,
  EnforcerNewRoute: EnforcerNewRoute,
  EnforcerIndexRoute: EnforcerIndexRoute,
}

const EnforcerRouteWithChildren = EnforcerRoute._addFileChildren(
  EnforcerRouteChildren,
)

interface TreasuryRouteChildren {
  TreasuryCashierRoute: typeof TreasuryCashierRoute
  TreasuryReportsRoute: typeof TreasuryReportsRoute
  TreasuryTransactionsRoute: typeof TreasuryTransactionsRoute
  TreasuryIndexRoute: typeof TreasuryIndexRoute
}

const TreasuryRouteChildren: TreasuryRouteChildren = {
  TreasuryCashierRoute: TreasuryCashierRoute,
  TreasuryReportsRoute: TreasuryReportsRoute,
  TreasuryTransactionsRoute: TreasuryTransactionsRoute,
  TreasuryIndexRoute: TreasuryIndexRoute,
}

const TreasuryRouteWithChildren = TreasuryRoute._addFileChildren(
  TreasuryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  EnforcerRoute: EnforcerRouteWithChildren,
  LoginRoute: LoginRoute,
  PnpRoute: PnpRoute,
  PortalRoute: PortalRoute,
  TreasuryRoute: TreasuryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
